In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import math

In [3]:
a = torch.Tensor([2,3,4])

In [4]:
#使用pytorch内置的softmax函数
softmax = a.softmax(dim=0)
print(softmax)
#根据公式计算
manual_softmax = torch.pow(math.e,a)/torch.pow(math.e,a).sum()
print(manual_softmax)

tensor([0.0900, 0.2447, 0.6652])
tensor([0.0900, 0.2447, 0.6652])


In [5]:
#使用pytorch内置的softmax函数log_softmax
log_softmax = a.log_softmax(dim=0)
print(log_softmax)
#根据公式计算
manual_log_softmax = (torch.pow(math.e,a)/torch.pow(math.e,a).sum()).log()
print(manual_log_softmax)

tensor([-2.4076, -1.4076, -0.4076])
tensor([-2.4076, -1.4076, -0.4076])


In [6]:
print(manual_log_softmax.unsqueeze(1))
#使用pytorch内置的nll_loss计算损失,reduction默认为mean，这里为了演示效果设置未能none
#LongTensor[0,0,0]表示正确类别所在索引，这里只有一个元素，方便演示，所以设置成了0
nll_loss = F.nll_loss(manual_log_softmax.unsqueeze(1),torch.LongTensor([0,0,0]),reduction='none')
#手动计算nll_loss
print(nll_loss)
#如果是多类别的
tmp = torch.Tensor([[-2.4076,4.52],
        [-1.4076,3.42],
        [-0.4076,0.123]])
tmp_index = torch.LongTensor([1,1,0])
print("nll_loss:{}".format(F.nll_loss(tmp,tmp_index,reduction='none')))

tensor([[-2.4076],
        [-1.4076],
        [-0.4076]])
tensor([2.4076, 1.4076, 0.4076])
nll_loss:tensor([-4.5200, -3.4200,  0.4076])


In [11]:
#交叉熵损失函数
x = torch.Tensor([[1,2],[0.5,3],[0.9,4]])
label = torch.LongTensor([0,1,0])
loss = nn.CrossEntropyLoss()
loss(x,label)

tensor(1.5121)

In [8]:
softmax = x.softmax(dim=1)
softmax

tensor([[0.2689, 0.7311],
        [0.0759, 0.9241],
        [0.0431, 0.9569]])

In [116]:
log = softmax.log()
log

tensor([[-1.3133, -0.3133],
        [-2.5789, -0.0789],
        [-3.1441, -0.0441]])

In [119]:
log_softmax = x.log_softmax(dim=1)
log_softmax

tensor([[-1.3133, -0.3133],
        [-2.5789, -0.0789],
        [-3.1441, -0.0441]])

In [111]:
F.nll_loss(x.log_softmax(dim=1),label)

tensor(1.5121)