In [39]:
import torch
import torch.nn as nn
import copy

In [47]:
A = torch.Tensor([[0.6,0.4],[0.7,0.3]])
B = copy.deepcopy(A)
for i in range(10):
    B = B.matmul(A)
    print(B.data.numpy())

[[0.64 0.36]
 [0.63 0.37]]
[[0.63600004 0.36400002]
 [0.637      0.363     ]]
[[0.6364001  0.36360002]
 [0.6363     0.36370003]]
[[0.63636005 0.36364007]
 [0.63637006 0.36363006]]
[[0.6363641  0.36363605]
 [0.6363631  0.36363706]]
[[0.63636374 0.3636365 ]
 [0.6363638  0.36363637]]
[[0.6363638  0.36363646]
 [0.63636374 0.36363646]]
[[0.6363638  0.3636365 ]
 [0.63636374 0.36363646]]
[[0.63636386 0.3636365 ]
 [0.63636374 0.36363646]]
[[0.63636386 0.3636365 ]
 [0.63636374 0.36363646]]


### 地球内部状态预测

In [48]:
import torch

In [129]:
#隐状态初始向量
startP = torch.Tensor([0.6,0.4])
#隐状态转移矩阵
A = torch.Tensor([[0.9,0.1],[0.95,0.05]])
#发射概率
B = torch.Tensor([[0.8,0.15,0.05],[0.2,0.3,0.5]])
#求S序列
#已知O={"大","小","中"}
#计算t1时刻的概率
stateP = startP*B[:,2]


In [130]:
stateP

tensor([0.0300, 0.2000])

In [139]:
#计算t2时刻的概率
torch.mm(stateP.transpose,A[:,0])

RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [140]:
A[:,0]

tensor([0.9000, 0.9500])

In [136]:
stateP

tensor([0.0300, 0.2000])

In [114]:
0.9000*0.03+0.2*0.95

0.217

In [98]:
stateP*A.transpose(0,1)

tensor([[0.0243, 0.1805],
        [0.0003, 0.0005]])

In [115]:
dir(A)

['__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ilshift__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rfloordiv__',
 '__rmul__',
 '__rpow__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setitem__',
 '__setstate_