In [1]:
import torch 

### 对y=x+b求偏导数

In [98]:
x = torch.ones((2,5),requires_grad=True)
b = 6
y = 6*x+b
holder_weights = torch.ones((2,5))
y.backward(holder_weights)
x.grad

tensor([[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]])

In [99]:
x = torch.ones((2,5),requires_grad=True)
b = 6
y = 6*x+b
holder_weights = torch.ones((2,5))
y.backward(holder_weights)
x.grad

tensor([[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]])

### 对sinx求导数

In [106]:
x = torch.ones((1,4),requires_grad=True)
y = torch.sin(x)
holder_weights = torch.ones((1,4))
y.backward(holder_weights)
x.grad

tensor([[0.5403, 0.5403, 0.5403, 0.5403]])

### 对指数函数y=e^x求导数

In [143]:
import math
x = torch.Tensor([[1,3],[2,4]])
x.requires_grad=True
y = torch.pow(math.e,x)
holder_weights = torch.ones_like(x)
y.backward(holder_weights)
x.grad

tensor([[ 2.7183, 20.0855],
        [ 7.3891, 54.5981]])

### 	对幂函数y=x^e求导

In [144]:
import math
x = torch.Tensor([[1,3],[2,4]])
x.requires_grad=True
y = torch.pow(x,math.e)
holder_weights = torch.ones_like(x)
y.backward(holder_weights)
x.grad

tensor([[ 2.7183, 17.9524],
        [ 8.9444, 29.4309]])

### 对数函数y=lnx求导数

In [145]:
import math
x = torch.Tensor([[1,3],[2,4]])
x.requires_grad=True
y = torch.log(x)
holder_weights = torch.ones_like(x)
y.backward(holder_weights)
x.grad

tensor([[1.0000, 0.3333],
        [0.5000, 0.2500]])

### sigmod的导数

In [146]:
import math
x = torch.Tensor([[1,3],[2,4]])
x.requires_grad=True
y = 1/(1+math.e**-x)
holder_weights = torch.ones_like(x)
y.backward(holder_weights)
x.grad

tensor([[0.1966, 0.0452],
        [0.1050, 0.0177]])